version: "3"

services:
    mariadb:
        container_name: mariadb
        build:
            context: ./requirements/mariadb/
            dockerfile: Dockerfile
        restart: always
        networks:
            - inception1
        env_file: .env
        environment:
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        volumes:
            - ~/Desktop/test/mysql:/var/lib/mysql

    wordpress:
        container_name: wordpress
        depends_on:
            - mariadb
        build:
            context: ./requirements/wordpress/
            dockerfile: Dockerfile
        restart: always
        networks:
            - inception1
        env_file: .env
        environment:
            - WORDPRESS_DB_HOST=mariadb:3306
            - WORDPRESS_DB_USER=${WP_DB_USER}
            - WORDPRESS_DB_NAME=${WP_DB_NAME}
            - WORDPRESS_DB_PASSWORD=${WP_DB_PW}
        volumes:
            - ~/Desktop/test/wordpress:/var/www/html

    nginx:
        container_name: nginx
        depends_on:
            - wordpress
        build:
            context: ./requirements/nginx/
            dockerfile: Dockerfile
        restart: always
        networks:
            - inception1
        ports:
            - 443:443
        env_file: .env
        volumes:
            - ~/Desktop/test/nginx:/etc/nginx/sites-available

networks:
    inception1:
        driver: bridge
